### ISSUE TITLE
Error in log of consumer when cache is deleted in development environment

### ISSUE THREAD

**Issue by TomasLudvik** [shopsys/shopsys#1300]
### What is happening
When you delete cache using `php phing clean` in `php-fpm` container in development environment there is high possibility that error will pop in your consumer log like this:

```
shopsys-framework-product-visibility-recalculate-consumer | PHP Warning:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: require(/var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/getVasekPurchart_ConsoleErrors_Console_ConsoleErrorListenerService.php): failed to open stream: No such file or directory in /var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/appDevDebugProjectContainer.php:2711
shopsys-framework-product-visibility-recalculate-consumer | Stack trace:
shopsys-framework-product-visibility-recalculate-consumer | #0 /var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/appDevDebugProjectContainer.php(2711): require()
shopsys-framework-product-visibility-recalculate-consumer | #1 /var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/appDevDebugProjectContainer.php(4893): ContainerMmxhxcl\appDevDebugProjectContainer->load('getVasekPurchar...')
shopsys-framework-product-visibility-recalculate-consumer | #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(229): ContainerMmxhxcl\appDevDebugProjectContainer->ContainerMmxhxcl\{closure}()
shopsys-framework-product-visibility-recalculate-consumer | #3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(61): Symfony\Component\EventDispatcher\EventDispatcher->sortListeners('console.termina...' in /var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/appDevDebugProjectContainer.php on line 2711
shopsys-framework-product-visibility-recalculate-consumer | PHP Fatal error:  ContainerMmxhxcl\appDevDebugProjectContainer::load(): Failed opening required '/var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/getVasekPurchart_ConsoleErrors_Console_ConsoleErrorListenerService.php' (include_path='/var/www/html/vendor/phing/phing/classes:.:/usr/local/lib/php') in /var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/appDevDebugProjectContainer.php on line 2711
shopsys-framework-product-visibility-recalculate-consumer | 14:15:50 CRITICAL  [php] Fatal Compile Error: ContainerMmxhxcl\appDevDebugProjectContainer::load(): Failed opening required '/var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/getVasekPurchart_ConsoleErrors_Console_ConsoleErrorListenerService.php' (include_path='/var/www/html/vendor/phing/phing/classes:.:/usr/local/lib/php') ["exception" => Symfony\Component\Debug\Exception\FatalErrorException { …}]
shopsys-framework-product-visibility-recalculate-consumer | 
shopsys-framework-product-visibility-recalculate-consumer | In appDevDebugProjectContainer.php line 2711:
shopsys-framework-product-visibility-recalculate-consumer |                                                                                
shopsys-framework-product-visibility-recalculate-consumer |   [Symfony\Component\Debug\Exception\FatalErrorException]                      
shopsys-framework-product-visibility-recalculate-consumer |   Compile Error: ContainerMmxhxcl\appDevDebugProjectContainer::load(): Failed  
shopsys-framework-product-visibility-recalculate-consumer |    opening required '/var/www/html/project-base/var/cache/dev/ContainerMmxhxc  
shopsys-framework-product-visibility-recalculate-consumer |   l/getVasekPurchart_ConsoleErrors_Console_ConsoleErrorListenerService.php' (  
shopsys-framework-product-visibility-recalculate-consumer |   include_path='/var/www/html/vendor/phing/phing/classes:.:/usr/local/lib/php  
shopsys-framework-product-visibility-recalculate-consumer |   ')                                                                           
shopsys-framework-product-visibility-recalculate-consumer |                                                                                
shopsys-framework-product-visibility-recalculate-consumer | 
shopsys-framework-product-visibility-recalculate-consumer | Exception trace:
shopsys-framework-product-visibility-recalculate-consumer |  () at /var/www/html/project-base/var/cache/dev/ContainerMmxhxcl/appDevDebugProjectContainer.php:2711
shopsys-framework-product-visibility-recalculate-consumer | 
shopsys-framework-product-visibility-recalculate-consumer | rabbitmq:consumer [-m|--messages [MESSAGES]] [-r|--route [ROUTE]] [-l|--memory-limit [MEMORY-LIMIT]] [-d|--debug] [-w|--without-signals] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <name>
```
This is caused because we delete all content of `var/cache/ directory in `clean` phing target. 

I have already tried these ways to fix this problem:
- use in framework.yml [`cache.prefix_seed`](https://symfony.com/doc/current/reference/configuration/framework.html#prefix-seed) but this does not work because we do not use symfony to delete cache, but we clear all content of that folder
- creating named volume in `docker-compose.yml` for `var/cache/dev` directory for each service, but this does not work because named volumes are created under root and application then does not have access to it
- silence this error in `ConsumerCommand` because it does not cause any harm and after error is triggered the consumer runs again. This did not work because it is Fatal error and no Exception. We have even tried to catch output of PHP but it did not work either.

### Expected result
There is no error in the log.

**Comment by TomasLudvik** [comment]
We have postponed PR with RabbitMQ and closed it, so this issue is no relevant anymore.
