### ISSUE TITLE
Error page generate throws confusing error when redis is not running

### ISSUE THREAD

**Issue by henzigo** [shopsys/shopsys#744]
### What is happening

If redis server is not running and i run `error-page-generate`, command throws confusing error "call get() on null" in [CartMigrationFacade](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Cart/CartMigrationFacade.php#L79) 
 
```
Shopsys Framework > error-pages-generate:
13:22:38 ERROR     [app] Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null (uncaught exception) at /var/www/html/vendor/shopsys/framework/src/Model/Cart/C
artMigrationFacade.php line 78 while running console command `shopsys:error-page:generate-all` ["exception" => Symfony\Component\Debug\Exception\FatalThrowableError { …}]
13:22:38 ERROR     [console] Error thrown while running command "shopsys:error-page:generate-all". Message: "Call to a member function get() on null" ["exception" => Error { …},"command" => "shopsys:
error-page:generate-all","message" => "Call to a member function get() on null"]
13:22:38 ERROR     [app] Command `shopsys:error-page:generate-all` exited with status code 1
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in /var/www/html/vendor/shopsys/framework/src/Model/Cart/CartMigrationFacade.
php:78
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Shopsys\FrameworkBundle\Model\Cart\CartMigrationFacade->onKernelController(Object(Symfony\Compo
nent\HttpKernel\Event\FilterControllerEvent), 'kernel.controll...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.controll...', Objec
t(Symfony\Component\HttpKernel\Event\FilterControllerEvent))
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.controll...', Object(Symfony\Componen
t\HttpKernel\Event\Filte in /var/www/html/vendor/shopsys/framework/src/Model/Cart/CartMigrationFacade.php on line 78
BUILD FAILED
/var/www/html/build.xml:250:85: Task exited with code 255
Total time: 1 minute  12.33 seconds
```

### Expected result

There should be condition that throws error if session is null with more relevant message

**Comment by boris-brtan** [comment]
was this already tested by @henzigo ????
